#!/bin/sh
#SBATCH -A ngi2016001
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10-00:00:00
#SBATCH -J rnaseq__PROJECT_
#SBATCH -o _ANALYSISDIR_/_PROJECT_/logs/rnaseq_%j.log

# Source NGI environment
source _ENVPATH_/conf/sourceme_upps.sh
source activate NGI

#set Nextflow env variables
export NXF_WORK=_ANALYSISDIR_/_PROJECT_/work
_REFDIR_
rnaseq -resume _CONFIG_ --genome _GENOME_ \
    --input _ANALYSISDIR_/_PROJECT_/_PROJECT_.SampleSheet.csv \
    --outdir _ANALYSISDIR_/_PROJECT_/results \
    --extra_trimgalore_args "--clip_r1 1 --clip_r2 1 --three_prime_clip_r1 1 --three_prime_clip_r2 1" _EXTRAARGS_

# some files get very restrictive permissions, so change them
chmod 660 _ANALYSISDIR_/_PROJECT_/results/pipeline_info/*
chgrp ngi2016001 _ANALYSISDIR_/_PROJECT_/results/pipeline_info/*
